/* Generated with cbindgen:0.29.0 */

Automatically generated by cbindgen

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

const char *rc_version(void);

void rc_free(uint8_t *ptr_out, uintptr_t len);

uint8_t *rc_process_bytes(uint32_t in_fmt,
                          uint32_t out_fmt,
                          const uint8_t *in_ptr,
                          uintptr_t in_len,
                          uintptr_t *out_len);
